// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qypjuwgzrjtkisisvbip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cGp1d2d6cmp0a2lzaXN2YmlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NjIwODMsImV4cCI6MjA1MjEzODA4M30.i4L2h2UrsOdIdaqrBbv1rOT5UR8twqdByxB0Dh9oZ2g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);